version: '2'
services:
  back:
    image: gcr.io/thelittlepedestrians-206020/tlp-back
    ports:
      - 3333:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - EMAIL_HOST=mailcatcher
      - EMAIL_PORT=25
      - NODE_ENV=production
    depends_on: 
      - mongo
      - mailcatcher
    networks:
      - mail
      - data
      - front

  front:
    image: gcr.io/thelittlepedestrians-206020/tlp-front
    environment:
      - SERVER_HOST=back
      - SERVER_PORT=3333
    ports:
      - 8080:80
    depends_on: 
      - back
    networks:
      - front

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - data

networks:
  front:
  data:
  mail:
