version: '2'
services:
  integrationtests:
    build:
      context: .
      dockerfile: integration-tests.Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - EMAIL_HOST=mailcatcher
      - EMAIL_PORT=25
      - NODE_ENV=development
    depends_on: 
      - mongo
      - mailcatcher
    volumes:
      - .:/tmp/app/
      - /tmp/app/node_modules
    networks:
      - mail
      - data

  back:
    build:
      context: .
      dockerfile: production.Dockerfile
    ports:
      - 3333:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - EMAIL_HOST=mailcatcher
      - EMAIL_PORT=25
      - NODE_ENV=production
    depends_on: 
      - mongo
      - mailcatcher
    networks:
      - mail
      - data
      - front

  front:
    image: the-little-pedestrians/tlp-front
    environment:
      - SERVER_HOST=back
      - SERVER_PORT=3333
    ports:
      - 8080:80
    depends_on: 
      - back
    networks:
      - front

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - data

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1080:80
      - 25:25
    networks:
      - mail

networks:
  front:
  data:
  mail:
