version: '2'
services:
  back:
    image: gcr.io/thelittlepedestrians-206020/tlp-back
    ports:
      - 3333:3000
    environment:
      - NODE_ENV=production
    depends_on: 
      - mongo

  front:
    image: gcr.io/thelittlepedestrians-206020/tlp-front
    environment:
      - SERVER_HOST=back
      - SERVER_PORT=3333
    ports:
      - 8080:80
    depends_on: 
      - back

  mongo:
    image: mongo
    ports:
      - 27017:27017
