apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: back
status:
  loadBalancer: {}
